### PR TITLE
Added event details, event list, router

### PR DESCRIPTION
**Pull request by tyagidivyam47**
write /cultural in url path to open cultural events list page.

### CODE REVIEW

**Comment by RamGoel** [comment]
Deploy Issues here, Please fix if possible

**Comment by tyagidivyam47** [comment]
After adding /cultural in the path it is showing page not found in the netlify build while it is working fine in local host.

**Comment by tyagidivyam47** [comment]
@RamGoel added a link of events in the footer to check the router. Data is yet to be filled in the cultural events and styling is incomplete

**Comment by RamGoel** [comment]
@tyagidivyam47 No issues, I'll do it

**Pull request merged**
